name = "freq51"
main = "index.js"
compatibility_date = "2025-09-01"

[assets]
directory = "book"
binding = "ASSETS"

# Build configuration
[build]
command = "curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.52/mdbook-v0.4.52-x86_64-unknown-linux-gnu.tar.gz | tar xvz && ./mdbook build"

# Environment variables (if needed)
[vars]
# Add any environment variables here
